import { useEffect, useState } from 'react';
import type { Config, Layout } from '../lib/types';
import type { Key, Translate } from '../i18n';
import { LayoutSelect } from '../components/LayoutSelect';
import { Icon } from '../components/Icon';

function Toggle({ title, description, checked, onChange }: { title: string; description?: string; checked: boolean; onChange: (v: boolean) => void }) {
  return <label className="setting-row"><span><strong>{title}</strong>{description && <small>{description}</small>}</span><input className="toggle" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /></label>;
}
export function Settings({ config, layouts, t, onSave, onRefresh }: { config: Config; layouts: Layout[]; t: Translate; onSave: (c: Config) => Promise<void>; onRefresh: () => void }) {
  const [layoutQuery, setLayoutQuery] = useState('');
  const [draft, setDraft] = useState(config); const [saving, setSaving] = useState(false);
  useEffect(() => setDraft(config), [config]);
  const update = <K extends keyof Config>(key: K, value: Config[K]) => setDraft(d => ({ ...d, [key]: value }));
  const boolean = (key: 'launchAtStartup' | 'minimizeToTray' | 'startMinimized' | 'notifications' | 'reduceMotion' | 'restoreClipboard' | 'debugLogs', help?: Key) => <Toggle key={key} title={t(key)} description={help ? t(help) : undefined} checked={draft[key]} onChange={v => update(key, v)} />;
  const dirty = JSON.stringify(draft) !== JSON.stringify(config);
  return <div className="page-content settings-page"><div className="page-heading"><span className="eyebrow">PIMXSWAP / {t('settings')}</span><h1>{t('settingsTitle')}</h1><p>{t('settingsDescription')}</p></div>
    <form onSubmit={async e => { e.preventDefault(); setSaving(true); try { await onSave(draft); } finally { setSaving(false); } }}>
      <section className="settings-section"><h2><Icon name="settings" />{t('general')}</h2>{boolean('launchAtStartup', 'launchAtStartupHelp')}{boolean('minimizeToTray', 'minimizeToTrayHelp')}{boolean('startMinimized')}{boolean('notifications')}</section>
      <section className="settings-section"><h2><Icon name="keyboard" />{t('language')}</h2><label className="setting-row"><strong>{t('appLanguage')}</strong><select value={draft.uiLanguage} onChange={e => update('uiLanguage', e.target.value as Config['uiLanguage'])}><option value="en">{t('english')}</option><option value="fa">{t('persian')}</option></select></label><div className="layout-pair"><LayoutSelect label={t('source')} value={draft.source} onChange={v => update('source', v)} layouts={layouts} t={t} /><LayoutSelect label={t('target')} value={draft.target} onChange={v => update('target', v)} layouts={layouts} t={t} /></div><div className="section-heading"><strong>{t('preferredLayouts')}</strong><button type="button" className="quiet" onClick={onRefresh}><Icon name="refresh" />{t('refresh')}</button></div><p className="hint">{t('preferredHelp')}</p><input className="layout-search" aria-label={t('searchLayouts')} placeholder={t('searchLayouts')} value={layoutQuery} onChange={e => setLayoutQuery(e.target.value)} /><div className="layout-chips">{layouts.filter(l => `${l.name} ${l.language}`.toLowerCase().includes(layoutQuery.toLowerCase())).map(l => <label key={l.id} className="layout-chip"><input type="checkbox" disabled={draft.preferredLayouts.length >= 32 && !draft.preferredLayouts.includes(l.id)} checked={draft.preferredLayouts.includes(l.id)} onChange={e => update('preferredLayouts', e.target.checked ? [...draft.preferredLayouts, l.id] : draft.preferredLayouts.filter(id => id !== l.id))} /><span>{l.name}<small dir="ltr">{l.id.slice(-8)}</small></span></label>)}</div>{!layouts.length && <p className="hint">{t('noLayouts')}</p>}</section>
      <section className="settings-section"><h2><Icon name="spark" />{t('shortcuts')}</h2>{(['autoHotkey', 'reverseHotkey', 'openHotkey'] as const).map((key, i) => <label className="setting-row" key={key}><strong>{t((['autoShortcut', 'reverseShortcut', 'openShortcut'] as const)[i])}</strong><input className="shortcut-input" dir="ltr" value={draft[key]} maxLength={70} onChange={e => update(key, e.target.value)} spellCheck={false} /></label>)}<p className="hint">{t('shortcutHelp')}</p></section>
      <section className="settings-section"><h2><Icon name="sun" />{t('appearance')}</h2><label className="setting-row"><strong>{t('theme')}</strong><select value={draft.theme} onChange={e => update('theme', e.target.value as Config['theme'])}>{(['dark', 'light', 'system'] as const).map(v => <option key={v} value={v}>{t(v)}</option>)}</select></label>{boolean('reduceMotion')}<label className="setting-row"><strong>{t('animationIntensity')}</strong><select value={draft.animationIntensity} onChange={e => update('animationIntensity', +e.target.value)}>{(['none', 'subtle', 'expressive'] as const).map((v, i) => <option key={v} value={i}>{t(v)}</option>)}</select></label></section>
      <section className="settings-section"><h2><Icon name="shield" />{t('advanced')}</h2>{boolean('restoreClipboard', 'restoreHelp')}<label className="setting-row threshold"><span><strong>{t('threshold')}</strong><small>{t('thresholdHelp')}</small></span><div><output>{Math.round(draft.threshold * 100)}%</output><input aria-label={t('threshold')} type="range" min="65" max="99" value={Math.round(draft.threshold * 100)} onChange={e => update('threshold', +e.target.value / 100)} /></div></label>{boolean('debugLogs', 'debugHelp')}</section>
      <div className="save-bar"><button type="button" className="quiet" disabled={!dirty || saving} onClick={() => setDraft(config)}>{t('discard')}</button><button className="primary" type="submit" disabled={!dirty || saving}><Icon name="check" />{t(saving ? 'saving' : 'save')}</button></div>
    </form></div>;
}
