import { useEffect, useRef, useState } from 'react';
import type { Config, Layout } from '../lib/types';
import type { Translate } from '../i18n';
import { LayoutSelect } from './LayoutSelect';
import { Icon, Logo } from './Icon';
export function Onboarding({ config, layouts, t, onSave, onLanguage }: { config: Config; layouts: Layout[]; t: Translate; onSave: (config: Config) => Promise<void>; onLanguage: (language: Config['uiLanguage']) => void }) {
  const [step, setStep] = useState(0); const [source, setSource] = useState(config.source); const [target, setTarget] = useState(config.target); const [busy, setBusy] = useState(false); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { ref.current?.focus(); }, [step]);
  return <div className="modal-backdrop"><div className="onboarding" role="dialog" aria-modal="true" aria-labelledby="onboarding-title" ref={ref} tabIndex={-1} onKeyDown={e => { if (e.key !== 'Tab') return; const all = Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),select,input') ?? []); all.push(...Array.from(document.querySelectorAll<HTMLElement>('[data-layout-popup] button,[data-layout-popup] input'))); const first = all[0], last = all.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }}><div key={step} className="onboarding-step"><div className="onboarding-mark"><Logo size={58} /></div><span className="eyebrow">{t('step')} {step + 1} / 3</span><h1 id="onboarding-title">{t((['welcome', 'chooseLanguages', 'setShortcut'] as const)[step])}</h1><p>{t((['welcomeDescription', 'chooseLanguagesDescription', 'setShortcutDescription'] as const)[step])}</p>{step === 0 && <div className="segmented"><button className={config.uiLanguage === 'en' ? 'selected' : ''} onClick={() => onLanguage('en')}>{t('english')}</button><button className={config.uiLanguage === 'fa' ? 'selected' : ''} onClick={() => onLanguage('fa')}>{t('persian')}</button></div>}{step === 1 && <div className="onboarding-layouts"><LayoutSelect label={t('source')} value={source} onChange={setSource} layouts={layouts} t={t} /><LayoutSelect label={t('target')} value={target} onChange={setTarget} layouts={layouts} t={t} />{layouts.length < 2 && <p className="hint">{t('chooseLanguagesDescription')}</p>}</div>}{step === 2 && <div className="onboarding-shortcuts"><label>{t('autoShortcut')}<input dir="ltr" defaultValue={config.autoHotkey} name="autoHotkey" form="onboarding-form" maxLength={70} /></label><kbd>{config.reverseHotkey}</kbd><small>{t('reverseShortcut')}</small></div>}</div><form id="onboarding-form" onSubmit={async e => { e.preventDefault(); if (step < 2) { setStep(step + 1); return; } const data = new FormData(e.currentTarget); setBusy(true); try { await onSave({ ...config, source, target, autoHotkey: String(data.get('autoHotkey') ?? config.autoHotkey), onboarded: true }); } finally { setBusy(false); } }}><div className="onboarding-actions">{step > 0 && <button type="button" className="quiet" onClick={() => setStep(step - 1)}>{t('back')}</button>}<button className="primary" disabled={busy || (step === 1 && (!source || !target))}>{t(step === 2 ? 'getStarted' : 'next')}<Icon name="arrow" /></button></div></form><div className="steps" aria-hidden="true">{[0, 1, 2].map(i => <span key={i} className={step === i ? 'active' : ''} />)}</div></div></div>;
}
